SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;

LOAD DATA LOCAL INFILE '/absolute/path/to/disease_bulk.csv'
  INTO TABLE disease
  CHARACTER SET utf8mb4
  FIELDS TERMINATED BY ','
  OPTIONALLY ENCLOSED BY '"'
  ESCAPED BY '\\'
  LINES TERMINATED BY '\n'
  IGNORE 0 LINES
  (code, `name`, name_en);

SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
